name = "auth-service"
main = "src/auth.js"
compatibility_date = "2025-07-04"
compatibility_flags = ["nodejs_compat"]
send_metrics = true
minify = true
workers_dev = true

[observability]
enabled = true

[env.staging]
name = "auth-service-staging"

[env.staging.observability]
enabled = true

[env.prod]
name = "auth-service-prod"

[env.prod.observability]
enabled = true 
