name = "fax-service"
main = "src/fax.js"
compatibility_date = "2025-07-04"
compatibility_flags = ["nodejs_compat"]
send_metrics = true
minify = false
workers_dev = false

[observability]
enabled = true

# R2 bucket binding for file storage (required for Telnyx provider)
[[r2_buckets]]
binding = "FAX_FILES_BUCKET"
bucket_name = "fax-files"
preview_bucket_name = "fax-files-preview"

[env.staging]
name = "fax-service-staging"

[env.staging.observability]
enabled = true

[env.staging.vars]
LOG_LEVEL = "DEBUG"
FAX_FILES_BUCKET_PUBLIC_URL = "https://pub-e22338f6c85449cea0f44573d2441665.r2.dev"
TELNYX_CONNECTION_ID = "2740858224415605884"
TELNYX_SENDER_ID = "+18334610414"

# Staging R2 bucket
[[env.staging.r2_buckets]]
binding = "FAX_FILES_BUCKET"
bucket_name = "fax-files-staging"
preview_bucket_name = "fax-files-staging-preview"

[env.prod]
name = "fax-service-prod" 
minify = true

[env.prod.observability]
enabled = true

# Production R2 bucket
[[env.prod.r2_buckets]]
binding = "FAX_FILES_BUCKET"
bucket_name = "fax-files-prod"
preview_bucket_name = "fax-files-prod-preview"
