name = "fax-service"
main = "src/fax.js"
compatibility_date = "2025-07-04"
compatibility_flags = ["nodejs_compat"]
send_metrics = true
minify = false
workers_dev = false

[observability]
enabled = true

[env.staging]
name = "fax-service-staging"

[env.staging.observability]
enabled = true


[env.prod]
name = "fax-service-prod" 
minify = true

[env.prod.observability]
enabled = true
