name = "send-fax-api"
main = "serverlessapigateway/src/index.js"
compatibility_date = "2025-07-04"
compatibility_flags = ["nodejs_compat"]
send_metrics = true
minify = true
workers_dev = true

kv_namespaces = [
  { binding = "CONFIG", id = "b07bdc1b33974cd2bd01feaff33c9688" }
]

services = [
  { binding = "FAX_SERVICE", service = "fax-service" },
  { binding = "ENV_TEST_SERVICE", service ="env-test-service" }
]

[observability]
enabled = true
head_sampling_rate = 1


[env.staging]
name = "send-fax-staging"
minify = true
workers_dev = false
route = { pattern = "api-staging.sendfax.pro", zone_name = "sendfax.pro", custom_domain = true  }

kv_namespaces = [
  { binding = "CONFIG", id = "9dcb081c93d8429f984b691ed3a293c5" }
]

services = [
  { binding = "FAX_SERVICE", service = "fax-service-staging" },
  { binding = "ENV_TEST_SERVICE", service ="env-test-service-staging" }
]

[env.staging.vars]
SUPABASE_URL = "https://vqdpahsrwtaccjozuchj.supabase.co"
LOG_LEVEL = "DEBUG"
FAX_PROVIDER = "telynx"
TELNYX_CONNECTION_ID = "2740858224415605884"
TELNYX_SENDER_ID = "+18334610414"

[env.prod]
name = "magicqrlink"
minify = true
workers_dev = false
route = { pattern = "api.sendfax.pro", zone_name = "sendfax.pro", custom_domain = true }
kv_namespaces = [
  { binding = "CONFIG", id = "b56a5a503127451398dc6868f183a0fe" }
]

services = [
  { binding = "FAX_SERVICE", service = "fax-service-prod" },
]

[env.prod.vars]
AUTH0_REDIRECT_URI="https://api.sendfax.pro/v1/auth/callback-redirect"
# Add missing environment variables for fax service
LOG_LEVEL = "INFO"
FAX_PROVIDER = "notifyre"
