name = "send-fax-api"
main = "serverlessapigateway/src/index.js"
compatibility_date = "2024-09-02"
send_metrics = true
minify = true
workers_dev = true


kv_namespaces =[
  { binding="CONFIG", id="47b431c1462449a29d05d9feb7eadc3d", preview_id = "64e1c0043bd041339932bcfa7de6df35"}
]

services = [
  { binding = "LINK_SERVICE", service = "link-service-test" },
  { binding = "ACCOUNT_SERVICE", service = "account-service-test" },
  { binding = "ANALYTICS_SERVICE", service = "analytics-service-test" },
  { binding = "SUBSCRIPTION_SERVICE", service = "subscription-service-test" }
]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
AUTH0_DOMAIN = "mqrlink.us.auth0.com"
AUTH0_CLIENT_ID= "mz0tS8ty8Gqys9UFAxn8I7jJUf88mv5b"
AUTH0_REDIRECT_URI = "https://magicqrlink-test.irensaltali.workers.dev/v1/auth/callback"


[env.staging]
name = "magicqrlink-staging"
minify = true
workers_dev = false
route = { pattern = "api-staging.magicqrlink.com", zone_name = "magicqrlink.com", custom_domain = true  }
kv_namespaces = [
  { binding="CONFIG", id="ba5d0c635af24533b089fbf8ac41d7e6"}
]

[env.staging.vars]
AUTH0_DOMAIN = "mqrlink.us.auth0.com"
AUTH0_CLIENT_ID= "mz0tS8ty8Gqys9UFAxn8I7jJUf88mv5b"
AUTH0_REDIRECT_URI="https://api-staging.magicqrlink.com/v1/auth/callback"

[env.prod]
name = "magicqrlink"
minify = true
workers_dev = false
route = { pattern = "api.magicqrlink.com", zone_name = "magicqrlink.com", custom_domain = true }
kv_namespaces = [
  { binding = "CONFIG", id = "1863fa3d004549e4800edeebeb36c0ff" }
]

[env.prod.vars]
AUTH0_REDIRECT_URI="https://api.magicqrlink.com/v1/auth/callback-redirect"
